enum ErrorId {
  // SERVER
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  // AUTH
  EMAIL_ALREADY_ASSIGNED = "EMAIL_ALREADY_ASSIGNED",
  INVALID_LOGIN_CREDENTIALS = "INVALID_LOGIN_CREDENTIALS",
  MISSING_TOKEN = "MISSING_TOKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
  // USERS
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  // WEIGHT-HISTORY
  WEIGHT_HISTORY_NOT_FOUND = "WEIGHT_HISTORY_NOT_FOUND",
}

export default ErrorId;
